// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package manager

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GrpcManagerClient is the client API for GrpcManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrpcManagerClient interface {
	// 服务控制
	ExecServiceControl(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	ExecEmqxControl(ctx context.Context, in *EmqxRequest, opts ...grpc.CallOption) (*EmqxResponse, error)
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (GrpcManager_UploadFileClient, error)
	GetService(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error)
}

type grpcManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcManagerClient(cc grpc.ClientConnInterface) GrpcManagerClient {
	return &grpcManagerClient{cc}
}

func (c *grpcManagerClient) ExecServiceControl(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/GrpcManager/ExecServiceControl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcManagerClient) ExecEmqxControl(ctx context.Context, in *EmqxRequest, opts ...grpc.CallOption) (*EmqxResponse, error) {
	out := new(EmqxResponse)
	err := c.cc.Invoke(ctx, "/GrpcManager/ExecEmqxControl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcManagerClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (GrpcManager_UploadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &GrpcManager_ServiceDesc.Streams[0], "/GrpcManager/UploadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &grpcManagerUploadFileClient{stream}
	return x, nil
}

type GrpcManager_UploadFileClient interface {
	Send(*UploadRequest) error
	CloseAndRecv() (*UploadResponse, error)
	grpc.ClientStream
}

type grpcManagerUploadFileClient struct {
	grpc.ClientStream
}

func (x *grpcManagerUploadFileClient) Send(m *UploadRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *grpcManagerUploadFileClient) CloseAndRecv() (*UploadResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *grpcManagerClient) GetService(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/GrpcManager/GetService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcManagerServer is the server API for GrpcManager service.
// All implementations must embed UnimplementedGrpcManagerServer
// for forward compatibility
type GrpcManagerServer interface {
	// 服务控制
	ExecServiceControl(context.Context, *Request) (*Response, error)
	ExecEmqxControl(context.Context, *EmqxRequest) (*EmqxResponse, error)
	UploadFile(GrpcManager_UploadFileServer) error
	GetService(context.Context, *ServiceRequest) (*ServiceResponse, error)
	mustEmbedUnimplementedGrpcManagerServer()
}

// UnimplementedGrpcManagerServer must be embedded to have forward compatible implementations.
type UnimplementedGrpcManagerServer struct {
}

func (UnimplementedGrpcManagerServer) ExecServiceControl(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecServiceControl not implemented")
}
func (UnimplementedGrpcManagerServer) ExecEmqxControl(context.Context, *EmqxRequest) (*EmqxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecEmqxControl not implemented")
}
func (UnimplementedGrpcManagerServer) UploadFile(GrpcManager_UploadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedGrpcManagerServer) GetService(context.Context, *ServiceRequest) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetService not implemented")
}
func (UnimplementedGrpcManagerServer) mustEmbedUnimplementedGrpcManagerServer() {}

// UnsafeGrpcManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcManagerServer will
// result in compilation errors.
type UnsafeGrpcManagerServer interface {
	mustEmbedUnimplementedGrpcManagerServer()
}

func RegisterGrpcManagerServer(s grpc.ServiceRegistrar, srv GrpcManagerServer) {
	s.RegisterService(&GrpcManager_ServiceDesc, srv)
}

func _GrpcManager_ExecServiceControl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcManagerServer).ExecServiceControl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GrpcManager/ExecServiceControl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcManagerServer).ExecServiceControl(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcManager_ExecEmqxControl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmqxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcManagerServer).ExecEmqxControl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GrpcManager/ExecEmqxControl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcManagerServer).ExecEmqxControl(ctx, req.(*EmqxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcManager_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GrpcManagerServer).UploadFile(&grpcManagerUploadFileServer{stream})
}

type GrpcManager_UploadFileServer interface {
	SendAndClose(*UploadResponse) error
	Recv() (*UploadRequest, error)
	grpc.ServerStream
}

type grpcManagerUploadFileServer struct {
	grpc.ServerStream
}

func (x *grpcManagerUploadFileServer) SendAndClose(m *UploadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *grpcManagerUploadFileServer) Recv() (*UploadRequest, error) {
	m := new(UploadRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GrpcManager_GetService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcManagerServer).GetService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GrpcManager/GetService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcManagerServer).GetService(ctx, req.(*ServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GrpcManager_ServiceDesc is the grpc.ServiceDesc for GrpcManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrpcManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GrpcManager",
	HandlerType: (*GrpcManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecServiceControl",
			Handler:    _GrpcManager_ExecServiceControl_Handler,
		},
		{
			MethodName: "ExecEmqxControl",
			Handler:    _GrpcManager_ExecEmqxControl_Handler,
		},
		{
			MethodName: "GetService",
			Handler:    _GrpcManager_GetService_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadFile",
			Handler:       _GrpcManager_UploadFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "grpc/manager/manager.proto",
}
